name: comiko_backend
description: Comiko backend project.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  comiko_shared:
    git: https://github.com/comiko-app/shared.git

dev_dependencies:
  test: ^0.12.0
